[package]
name = "vzljot_opcua"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
pico-args = { version = "0.5"}
rand.workspace = true
chrono.workspace = true
async-trait = { workspace = true }

[dependencies.async-opcua]
path = "../async-opcua"
features = ["all"]

[lints]
workspace = true
