[package]
name = "vzljot_opcua"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
pico-args = { version = "0.5"}
rand.workspace = true
chrono.workspace = true
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

async-opcua-client = { path = "../async-opcua-client", optional = true, version = "0.18.0" }
async-opcua-core = { path = "../async-opcua-core", version = "0.18.0" }
async-opcua-core-namespace = { path = "../async-opcua-core-namespace", optional = true, version = "0.18.0" }
async-opcua-crypto = { path = "../async-opcua-crypto", version = "0.18.0" }
async-opcua-nodes = { path = "../async-opcua-nodes", version = "0.18.0" }
async-opcua-types = { path = "../async-opcua-types", version = "0.18.0" }
async-opcua-server = { path = "../async-opcua-server", version = "0.18.0" }

[dependencies.async-opcua]
path = "../async-opcua"
features = ["all"]

[lints]
workspace = true
